spring.application.name=auth-service
server.port=8081

# Security Config
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/master

# Database Config
spring.datasource.url=jdbc:postgresql://localhost:5433/auth-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Keycloak
keycloak.admin.client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET}
keycloak.admin.client-id=${KEYCLOAK_ADMIN_CLIENT_ID}
keycloak.frontend-client-id=${KEYCLOAK_FRONTEND_CLIENT_ID}
keycloak.base-url=${KEYCLOAK_BASE_URL}
keycloak.realm=${KEYCLOAK_REALM}