spring.application.name=gateway-service
server.port=8082

jwt.secret=random-random-bs-bs-what-do-you-know-i-know-a-lot-of-stuff

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=space-service
spring.cloud.gateway.routes[1].uri=http://localhost:8080
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/**