spring.application.name=gateway-service
server.port=8082

jwt.secret=${JUNO_JWT_SECRET}

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=${JUNO_SPRING_CLOUD_GATEWAY_AUTH_SVC}
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=space-service
spring.cloud.gateway.routes[1].uri=${JUNO_SPRING_CLOUD_GATEWAY_SPACE_SVC}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/**

# CORS
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:3000,https://hijuno.vercel.app
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true