services:
  postgres:
    image: postgres:16
    container_name: auth-postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-db
    ports:
      - "5433:5432"
    volumes:
      - ./data/data:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: auth-keycloak
    ports:
      - "9090:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/auth-db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_URL: http://localhost:9090
    env_file:
      - .env
    command: start-dev
    volumes:
      - ./keycloak/data:/opt/keycloak/data
    depends_on:
      - postgres

volumes:
  data:
  keycloak: