apiVersion: apps/v1
kind: Deployment
metadata:
  name: juno-space-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: juno-space-service
  template:
    metadata:
      labels:
        app: juno-space-service
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: space-service
          image: bom.ocir.io/bmgq8vucgdtj/juno-space-service:1.1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/juno-space-service

            - name: SPRING_DATASOURCE_USERNAME
              value: admin

            - name: SPRING_DATASOURCE_PASSWORD
              value: admin123
---
apiVersion: v1
kind: Service
metadata:
  name: juno-space-service
spec:
  selector:
    app: juno-space-service
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer