spring.application.name=space-service
server.port=8080

# Database Config

spring.datasource.url=jdbc:postgresql://localhost:5432/space-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=space-service
spring.kafka.consumer.auto-offset-reset=latest

jwt.secret=${JUNO_JWT_SECRET}